server:
  port : 1999
       
         
spring:
  application:
    name: KPL-SERVICE
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/kpl_2023_main_db
    password: 1234
    tomcat.max-active: 2
    hikari:
      maximum-pool-size: 2
      auto-commit: true

  jpa:
    generate-ddl: 'true'
    database-platform:  org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update


#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: kpl2023prod@gmail.com
#    password: vhijfojqbbzygyvi
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000 
          connctiontimeout: 5000
          writetimeout: 5000
       
    host: smtp.gmail.com    
    username: kpl2023prod@gmail.com
    password: vhijfojqbbzygyvi
    port: 587
    


jwt_secret: 87067a5c90101b420dcbdcaa90f1115452bca49a28c9d1bb1ef66c5a04949321
jwt_expire: 600000000000
springfox:
  documentation:
    swagger-ui:
      base-url: /kplService 